# Generated by Django 3.2 on 2021-04-29 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 23, 55, 3, 24780, tzinfo=utc))),
            ],
        ),
    ]
