# Generated by Django 3.2 on 2021-04-29 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
