# Generated by Django 3.2 on 2021-04-30 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 0, 1, 55, 642223, tzinfo=utc)),
        ),
    ]
