# Generated by Django 3.2 on 2021-04-30 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='data',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 0, 12, 8, 87960, tzinfo=utc)),
        ),
    ]
